apiVersion: v1
kind: Template
metadata:
  name: ${APP_NAME}
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
      build: ${APP_NAME}
    name: ${NAME}
  spec:
    output:
      to:
        kind: DockerImage
        name: ${REGISTRY_URL}${APP_NAME}:${APP_VERSION}
      pushSecret:
        name: ${PUSH_SECRET}
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi  
    source:
      git:
        ref: ${BRANCH_NAME}
        uri: ${SOURCE_REPOSITORY_URL}
      sourceSecret:
        name: ${SOURCE_SECRET_NAME}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: ${FROM_IMAGE}
        pullSecret:
          name: ${PUSH_SECRET}
      type: Docker
parameters:
- name: APP_NAME
  displayName: Application Name
  description: Unique application name
  required: true
- name: NAME
  displayName: Application Name
  description: Unique application name
  required: true
- name: APP_VERSION
  displayName: Application Version
  description: Unique application version
  required: true
- name: SOURCE_REPOSITORY_URL
  displayName: Source Repository URL
  description: The URL of the repository with your application source code
  required: true
- name: SOURCE_SECRET_NAME
  displayName: Source Secret Name
  description: Secret to be used for connecting to source repo
  value: bitbucket-secret
  required: true
  required: true
- name: BRANCH_NAME
  displayName: SCM Branch Name
  description: The branch to be built
  required: true
- name: REGISTRY_URL
  displayName: OpenShift Container Registry
  description: OpenShift Container Registry
  required: false
- name: PUSH_SECRET
  displayName: Secret for pushing to registry
  description: Secret for pushing to registry
  value: nexus-secret
  required: true
- name: CONTEXT_DIR
  displayName: Path for Dockerfile
  description: Path for Dockerfile
  required: false
- name: FROM_IMAGE
  displayName: FROM IMAGE
  description: From image used in your dockerfile
  value: nginx:latest
  required: true
