apiVersion: v1
kind: Template
metadata:
  name: ${APP_NAME}
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: ${APP_NAME}
      port: 8080
      targetPort: 8080
      protocol: TCP
    selector:
      app: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    host: ${HOST_NAME}
    path: ${ROUTE_PATH}
    port:
      targetPort: ${APP_NAME}
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          appversion: ${APP_VERSION}
        name: ${APP_NAME}
      spec:
        containers:
        - image: "${REGISTRY_URL}${NAME}:${APP_VERSION}"
          name: ${APP_NAME}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: ${PROFILE_NAME}
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 500Mi
              cpu: 500m
        dnsPolicy: ClusterFirst
        imagePullSecrets:
          - name: ${PULL_SECRET}
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - type: ConfigChange    
parameters:
- name: APP_NAME
  displayName: Application Name
  description: Unique application name
  required: true
- name: NAME
  displayName: Application Name
  description: Unique application name
  required: true
- name: NAMESPACE
  displayName: Project Namespace
  description: Project namespace
  required: true
- name: REGISTRY_URL
  displayName: Docker Registry URL
  description: The URL of the registry to push the image to
  required: true
- name: APP_VERSION
  displayName: Application Version
  description: Unique application version
  value: latest
  required: true
- name: PULL_SECRET
  displayName: Secret for pulling from registry
  description: Secret for pulling from registry
  value: nexus-secret
  required: true
- name: ROUTE_PATH
  displayName: route path
  description: route path
  required: true
- name: PROFILE_NAME
  displayName: spring profile name
  description: spring profile name
  value: vodafone
  required: false
- name: HOST_NAME
  displayName: Domain name for routh url
  description: Domain name for routh url
  required: false
